const PERIODS = {
    "IB":"Italo-Byzantine",
    "15":"15 Cen North Renaissance",
    "16":"16 Cen North Renaissance",
    "ER":"Early Renaissance",
    "HR":"High Renaissance",
    "VR":"Venetian Renaissance",
    "MAN":"Mannerism",
    "NB":"Northern Baroque",
    "SB":"Southern Baroque",
    "Arch_R":"Renaissance Architecture",
    "Arch_B":"Baroque Architecture"
};


var galleryData = [
    {
        "name":"Birth of Robert Harris Jr.",
        "year": 1807,
        "month": 11,
        "day": 26,
        "loc": "Hucclecote, Gloucestershire, England",
        "recId": 'earlyYears',
        "type":"int",
        "pos": 25,
        "img":null,
    },
    {
        "name": "Christening of Robert Harris Jr.",
        "year": 1808,
        "month": 01,
        "day": 21,
        "loc": "Churchdown, Gloucestershire, England",
        "recId": 'earlyYears',
        "type": "int",
        "pos": 25,
        "img": null,
    },
    {
        "name":"Methodist Marriage",
        "year": 1835,
        "month": 02,
        "day": 18,
        "loc": "Gloucestershire, England",
        "recId": 'marriage',
        "type":"int",
        "pos": 25,
        "img":null,
    },
    {
        "name":"Church of England Marriage",
        "year": 1835,
        "month": 08,
        "day": 28,
        "loc": "Gloucestershire, England",
        "recId": 'marriage',
        "type":"int",
        "pos": 25,
        "img":null,
    },
    {
        "name":"Elevation of the Cross",
        "year":1810,
        "month":0,
        "day":0,
        "type":"int",
        "pos":50,
        "img":"https://o.quizlet.com/i/sgB7SKqS15aXFivmVHuUzg.jpg",
        "period":"Northern Baroque",
    },
]