var galleryData = [
    {
        "name":"Letter to Hannah",
        "year":1846,
        "month":08,
        "day":28,
        "type":"int",
        "pos":30,
        "img":"images/letter_crop.png",
        "period":"Northern Baroque",
    },
    {
        "name":"Marriage Record",
        "year":1835,
        "month":08,
        "day":28,
        "type":"int",
        "pos":30,
        "img":"images/wedding_record.png",
        "period":"Northern Baroque",
    },
    {
        "name":"St Mary de Lode",
        "year":1833,
        "month":08,
        "day":28,
        "type":"int",
        "pos":15,
        "img":"images/St_Mary_de_Lode_Church.png",
        "period":"Northern Baroque",
    },
    {
        "name":"Church of England Marriage",
        "year": 1835,
        "month": 08,
        "day": 28,
        "loc": "Gloucestershire, England",
        "recId": 'marriage',
        "type":"int",
        "pos": 50,
        "img":null,
    },
    {
        "name":"Methodist Marriage",
        "year": 1835,
        "month": 02,
        "day": 18,
        "loc": "Gloucestershire, England",
        "recId": 'marriage',
        "type":"int",
        "pos": 65,
        "img":null,
    },
    {
        "name":"Hannah Mariah Eagles",
        "year":1828,
        "month":null,
        "day":null,
        "type":"int",
        recId: "fallingInLove",
        "pos":15,
        "img":"images/hannah.png",
    },
    {
        "name":"Robert becomes a Pugilist",
        "year":1825,
        "month":null,
        "day":null,
        recId: "pugilism",
        "type":"int",
        "pos":35,
        "img":"images/pugilism.jpg",
    },
    {
        "name":"Area Around Gloucestershire",
        "year":1810,
        "month":null,
        "day":null,
        "type":"int",
        "pos":50,
        "img":"images/gloucestershire_map.png",
        "period":"Northern Baroque",
    },
    {
        "name": "The True Chuch is Restored",
        "year": 1830,
        "month": 03,
        "day": 6,
        "loc": null,
        "recId": null,
        "type": "ext",
        "pos": 25,
        "img": null,
    },
    {
        "name": "Christening of Robert Harris Jr.",
        "year": 1808,
        "month": 01,
        "day": 21,
        "loc": "Churchdown, Gloucestershire, England",
        "recId": 'earlyYears',
        "type": "int",
        "pos": 10,
        "img": null,
    },
    {
        "name":"Birth of Robert Harris Jr.",
        "year": 1807,
        "month": 11,
        "day": 26,
        "loc": "Hucclecote, Gloucestershire, England",
        "recId": 'earlyYears',
        "type":"int",
        "pos": 25,
        "img":null,
    },
]